### ISSUE TITLE
Define goals and requirements for t-log module

### ISSUE THREAD

**Issue by katia-e** [zero-os/0-tlog#4]
Create a document explaining philosophy, goals, features and methods of the transaction server from the conceptual viewpoint.

### Goal: 
The document is meant to summarize the current vision of the future t-log module architecture. This document will be used to define necessary changes in current version and guide actual implementation.

### Source: 
The document is based on the recording of the meeting from 15.11.17

**Comment by katia-e** [comment]
# Introduction


T-log or a transactional server is used by a server generating data in order to store and replicate transaction logs. In case  the server fails, data can be recovered by replaying transaction logs, recorded by the t-log server. T-log design has to allow for secure and fast way to store and replicate transaction logs. The server generating data employs t-log client to communicate with a t-log server, located remotely.

In fact, t-log is a memory aggregator that builds containers following the requested profile.

# Main design aspects
## T-log module logic

-  Support two transactional servers. In general case, single t-log can ensure reliability, as the chance of both nodes to fail at the same time is neglectable. However, there should be possibility to set up two or more transactional servers in case if it is required by a customer. 

- Main server is writing transactional logs synchronously to the remote t-log server over TCP, or possibly using Intel SPDK. Reply-request communication between server and client must me avoided. Client has to keep open different sockets for sending data and control channel.

- Transactional servers are independent from each other, allowing for asynchronous replication of the transactional logs. It is responsibility of the client to keep markers to know which container has been sent to which transactional server. These markers play role of the only point of synchronization. With markers the client can see the state of each t-log. The server keeps data in memory until t-log client receives the conformation from the corresponding transactional server that data is successfully flushed. If one of the transactional servers is out, and the data was not flushed (no conformation was received), it has to be resent to another transactional server.

- Synchronization of transactional servers. T-log servers know about each other and communicate to avoid replication the same data.

- Each transactional server is stateless. Beginning of the session:  client sends config information (block size to flush, how often to flush the blocks, 0-store config to write to at the backend, behaviour of t-log), as response the transactional server creates container. Ones data was successfully flashed the server receives back metadata file from 0-store. If the session fails, client can connect to another t-log server with the same config and send data again.

- Reservation mechanism must be on storage level.

- Transaction server has to encrypt metadata with given key.

## Metadata layer design

- Metadata coming back from the transactional server can be stored in blockchain. This creates a distributed database that contains its history.

- Metadata store is a directory store, each object is a directory.

- A customer can subscribe to a t-log server for asynchronous replication and fetch the data of interest from the data base. All changes sent to the t-log are reflected on the public ledger. Metadata from the ledger can be used to rebuild data on the local machine of the customer on request.

- Security: only relevant client can fetch the information from the transactional server, because the metadata is encrypted with private key of the creator.

- Users and groups are entries with their public keys. Together with user database it gives users' identities and mapping between keys and identities.

## Key-value storage

- Key-value store has to be implemented as redundant global distributed database, acting as a blockchain for storing data (without transactions). Global consensus is not necessary, consensus can be achieved for a given namespace or group. In fact this blockchain consists of multiple blockchains defined for groups and namespaces.

- Validating of the block chain can be done as an external paid service. Validators store the archive of the blockchain and validate it, but they are not a part of the chain.

**Comment by katia-e** [comment]
Open PR https://github.com/zero-os/0-tlog/pull/5

**Comment by zaibon** [comment]
fixed by https://github.com/zero-os/0-tlog/commit/e9cb2e77876619e1cb96b36a66aba4fecffa6fd8
